
  - name: Interfaccia Bonooser
    hosts: localhost
    gather_facts: false
    become: no

    vars:
      bonoos_csv: interfaccia_bonoos.csv
      sftp_extra: "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"
      sftp_key: bonos.key
      api_key: "ODIyOWQ1NmEtOT5Zi1hODY3LTc1OGNjMTYwNDQyOA=="

    tasks:

    - name: Get bonoos_csv from Sftp hr.zucchetti.com
      ansible.builtin.command: "sftp -i {{ sftp_key }} {{ sftp_extra }} sftptecniplast@hr.zucchetti.com:/pub/{{ bonoos_csv }} {{ bonoos_csv }}"
