  - name: Interfaccia Bonooser
    hosts: localhost
    gather_facts: yes
    become: no


    tasks:

    - name: Remove file (bonoos_csv)
      ansible.builtin.file:
        path: "{{ bonoos_csv }}"
        state: absent
